### ISSUE TITLE
kubegres operator crashes with blank spec.replicas

### ISSUE THREAD

**Issue by blushingpenguin** [reactive-tech/kubegres#69]
I had the config below with spec.replicas being blank.

```yaml
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: pg
  namespace: dev
spec:
  replicas: 
  image: postgres:14
  database:
    size: 2Gi
  customConfig: pg-config
  resources:
    limits:
      memory: 300Mi
    requests:
      memory: 200Mi
  env:
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pg-auth
        key: superUserPassword
  - name: POSTGRES_REPLICATION_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pg-auth
        key: replicationUserPassword
```

which causes the operator to crash with the stack trace below:

```
2021-11-25T10:52:46.363Z	INFO	controllers.Kubegres	KUBEGRES	{"name": "pg", "Status": {"blockingOperation":{"statefulSetOperation":{},"statefulSetSpecUpdateOperation":{}},"previousBlockingOperation":{"statefulSetOperation":{},"statefulSetSpecUpdateOperation":{}}}}
E1125 10:52:46.464207       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 330 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x15fcee0, 0x230b770)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:48 +0x89
panic(0x15fcee0, 0x230b770)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
reactive-tech.io/kubegres/controllers/states/statefulset.(*StatefulSetsStates).loadStates(0xc00148c040, 0x0, 0x0)
	/workspace/controllers/states/statefulset/StatefulSetsStates.go:61 +0x7b
reactive-tech.io/kubegres/controllers/states/statefulset.LoadStatefulSetsStates(...)
	/workspace/controllers/states/statefulset/StatefulSetsStates.go:49
reactive-tech.io/kubegres/controllers/states.(*ResourcesStates).loadStatefulSetsStates(0xc00148d370, 0xc0000786c0, 0x19b3ba0)
	/workspace/controllers/states/ResourcesStates.go:85 +0xc5
reactive-tech.io/kubegres/controllers/states.(*ResourcesStates).loadStates(0xc00148d370, 0xc0009b6a20, 0x0)
	/workspace/controllers/states/ResourcesStates.go:56 +0x1a5
reactive-tech.io/kubegres/controllers/states.LoadResourcesStates(...)
	/workspace/controllers/states/ResourcesStates.go:40
reactive-tech.io/kubegres/controllers/ctx/resources.CreateResourcesContext(0xc0005da000, 0x19b3ba0, 0xc00140b290, 0x19bc6c0, 0xc000046e60, 0x19c7440, 0xc00022d0e0, 0x19b09e0, 0xc0004e6600, 0x0, ...)
	/workspace/controllers/ctx/resources/ResourcesContext.go:108 +0x8a5
reactive-tech.io/kubegres/controllers.(*KubegresReconciler).Reconcile(0xc0004e6640, 0x19b3ba0, 0xc00140b290, 0xc001402479, 0x3, 0xc00140246c, 0x2, 0xc00140b290, 0x40a1ff, 0xc000030000, ...)
	/workspace/controllers/kubegres_controller.go:74 +0x17f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002de000, 0x19b3ae0, 0xc000394e00, 0x16536c0, 0xc00140cd40)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:263 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002de000, 0x19b3ae0, 0xc000394e00, 0xc000056e00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x19b3ae0, 0xc000394e00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:198 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000056f50)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00149ff50, 0x197e0c0, 0xc00140b170, 0xc000394e01, 0xc00043ade0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000056f50, 0x3b9aca00, 0x0, 0x1, 0xc00043ade0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x19b3ae0, 0xc000394e00, 0xc0013fdc50, 0x3b9aca00, 0x0, 0x1)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x19b3ae0, 0xc000394e00, 0xc0013fdc50, 0x3b9aca00)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:195 +0x4e7
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14aa7db]

goroutine 330 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x15fcee0, 0x230b770)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
reactive-tech.io/kubegres/controllers/states/statefulset.(*StatefulSetsStates).loadStates(0xc00148c040, 0x0, 0x0)
	/workspace/controllers/states/statefulset/StatefulSetsStates.go:61 +0x7b
reactive-tech.io/kubegres/controllers/states/statefulset.LoadStatefulSetsStates(...)
	/workspace/controllers/states/statefulset/StatefulSetsStates.go:49
reactive-tech.io/kubegres/controllers/states.(*ResourcesStates).loadStatefulSetsStates(0xc00148d370, 0xc0000786c0, 0x19b3ba0)
	/workspace/controllers/states/ResourcesStates.go:85 +0xc5
reactive-tech.io/kubegres/controllers/states.(*ResourcesStates).loadStates(0xc00148d370, 0xc0009b6a20, 0x0)
	/workspace/controllers/states/ResourcesStates.go:56 +0x1a5
reactive-tech.io/kubegres/controllers/states.LoadResourcesStates(...)
	/workspace/controllers/states/ResourcesStates.go:40
reactive-tech.io/kubegres/controllers/ctx/resources.CreateResourcesContext(0xc0005da000, 0x19b3ba0, 0xc00140b290, 0x19bc6c0, 0xc000046e60, 0x19c7440, 0xc00022d0e0, 0x19b09e0, 0xc0004e6600, 0x0, ...)
	/workspace/controllers/ctx/resources/ResourcesContext.go:108 +0x8a5
reactive-tech.io/kubegres/controllers.(*KubegresReconciler).Reconcile(0xc0004e6640, 0x19b3ba0, 0xc00140b290, 0xc001402479, 0x3, 0xc00140246c, 0x2, 0xc00140b290, 0x40a1ff, 0xc000030000, ...)
	/workspace/controllers/kubegres_controller.go:74 +0x17f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002de000, 0x19b3ae0, 0xc000394e00, 0x16536c0, 0xc00140cd40)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:263 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002de000, 0x19b3ae0, 0xc000394e00, 0xc000056e00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x19b3ae0, 0xc000394e00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:198 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000056f50)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00149ff50, 0x197e0c0, 0xc00140b170, 0xc000394e01, 0xc00043ade0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000056f50, 0x3b9aca00, 0x0, 0x1, 0xc00043ade0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x19b3ae0, 0xc000394e00, 0xc0013fdc50, 0x3b9aca00, 0x0, 0x1)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x19b3ae0, 0xc000394e00, 0xc0013fdc50, 0x3b9aca00)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:195 +0x4e7
```

**Comment by alex-arica** [comment]
I will add a not null check during the next release.

**Comment by blushingpenguin** [comment]
Sorry, I should have said -- it's fine if I set a value, not having one was a mistake

**Comment by alex-arica** [comment]
Kubegres version 1.14 is available with the changes that we discussed about in this issue. When the field `spec.replicas` is left blank, Kubegres will not crash and it will display the following validation error message:
```
{"error": "In the Resources Spec the value of 'spec.replicas' is undefined. Please set a value otherwise this operator cannot work correctly."}
```

Please see the release page: 
https://github.com/reactive-tech/kubegres/releases/tag/v1.14

Thank you @blushingpenguin for your reporting this issue.

To install Kubegres 1.14, please run:
```
kubectl apply -f https://raw.githubusercontent.com/reactive-tech/kubegres/v1.14/kubegres.yaml
```

I am closing this issue.
